version: '3'
services:
  webtest:
    build: .
    image: stellarity/webtest
    volumes:
      - ~/.m2:/root/.m2
      - ~/.gradle/caches/modules-2:/root/.gradle/caches/modules-2
      - ~/.gradle/wrapper:/root/.gradle/wrapper
